#!/usr/bin/Rscript
#  R/label_keys.R Author "Nathan Wycoff <nathanbrwycoff@gmail.com>" Date 06.27.2018
id_to_pretty <- list(
    "auth" = "Authentic Leadership (AL)",
    "auth_bp" = "Balanced Processing (AL)",
    "auth_imp" = "Internalized Moral Perspective (AL)",
    "auth_rt" = "Relational Transparency (AL)",
    "auth_sa" = "Self-Awareness (AL)",
    "ili" = "Identity Leadershp Inventory",
    "ili_champ" = "Identity Advancement (IL)",
    "ili_emb" = "Identity Impresarioship (IL)",
    "ili_ent" = "Identity Entrepreneurship (IL)",
    "ili_pro" = "Identity Prototypicality (IL)",
    "lnr" = "Leadership Non-Resistance (LNR)",
    "tfl" = "Transformational Leadership (TFL)",
    "tfl_insp" = "Inspirational Motivation (TL)",
    "tfl_int" = "Intellectual Stimulation (TL)",
    "tfl_pers" = "Personal Recognition (TL)",
    "tfl_sup" = "Supportive Leadership (TL)",
    "tfl_vis" = "Vision (TL)",
    "grt" = "Grit (Grit-S)",
    "brs" = "Psychological Resilience (BRS)",
    "sc.hw" = "Self-Control (SSCCS)",
    "uh" = "Unconditional Happiness (UHS)",
    "uh.vmi" = "School-Specific UH",
    "dis" = "Discomfort Intolerance (DIS)",
    "ffmq" = "Mindfulness Total (FFMQ)",
    "ffmq_aa" = "Acting with Awareness (FFMQ)",
    "ffmq_de" = "Describing (FFMQ)",
    "ffmq_nj" = "Nonjudging (FFMQ)",
    "ffmq_nr" = "Nonreactivity (FFMQ)",
    "ffmq_ob" = "Observing (FFMQ)",
    "mt" = "Mental Toughness (MTI)",
    "har" = "Hardiness (DRS)",
    "leadChal" = "Mentally Tough Leadership (MTLS)",
    "bfi_agree" = "Agreeableness (BFI)",
    "bfi_consc" = "Conscientiousness (BFI)",
    "bfi_extrav" = "Extraversion (BFI)",
    "bfi_neur" = "Emotional Stability (BFI)",
    "bfi_open" = "Openness to Experience (BFI)"
    )

#id_to_pretty <- list(
#                     "dis" = "Discomfort Intolerance (DIS)",
#                     "ffmq" = "Mindfulness (FFMQ)",
#                     "uh" = "Unconditional Happiness (UHS)",
#                     "leadChal" = "Mentally Tough Leadership",
#                     "lnr" = "Leadership Nonresistance (LNR)",
#                     "mt" = "Mentally Toughness",
#                     "brs" = "Psychological Resilience",
#                     "sc.hw" = "Self-Control (SSCCS)",
#                     "uh.vmi" = "School-specific UH",
#                     "auth_bp" = "Balanced Processing",
#                     "auth_imp" = "Internalized Moral Perspective",
#                     "auth_rt" = "Relational Transparency",
#                     "auth_sa" = "Self-Awareness",
#                     "ili_champ" = "ili_champ",
#                     "ili_emb" = "ili_emb",
#                     "ili_ent" = "Identity Entrepreneurship",
#                     "ili_pro" = "Identity Prototypicality",
#                     "tfl_id" = "tfl_id",
#                     "tfl_insp" = "Inspirational Communication",
#                     "tfl_int" = "Intellectual Stimulation",
#                     "tfl_pers" = "Personal Recognition",
#                     "tfl_sup" = "Supportive Leadership",
#                     "tfl_vis" = "Vision",
#                     "bfi_consc" = "Conscientiousness (BFI)",
#                     "grt" = "Grit (Grit-S)",
#                     "har" = "Hardiness (DRS)",
#                     "bfi_agree" = "Agreeableness (BFI)",
#                     "bfi_extrav" = "Extraversion (BFI)",
#                     "bfi_neur" = "Neuroticism (BFI)",
#                     "bfi_open" = "Openness to Experience (BFI)"
#                     )
